version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pancakes-unlimited-docker:pu-spring-docker
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://pancakes-unlimited-server.database.windows.net:1433;database=pancakes-unlimited-database
      SPRING_DATASOURCE_USERNAME: super
      SPRING_DATASOURCE_PASSWORD: Otl1.xTsh]0#
      SPRING_LIQUIBASE_URL: jdbc:sqlserver://pancakes-unlimited-server.database.windows.net:1433;databaseName=pancakes-unlimited-database;encrypt=true;trustServerCertificate=false;loginTimeout=30;
      SPRING_LIQUIBASE_USER: super
      SPRING_LIQUIBASE_PASSWORD: Otl1.xTsh]0#
      SPRING_JPA_HIBERNATE_DDL_AUTO: none

# try to use the below variables as env var instead of the above
# environment variables and see if it works

#  db:
#    container_name: postgres-db
#    image: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: super
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: pancakes-unlimited-database